In [51]:
# read CSV

import pandas as pd
# df = pd.read_csv('testSVD_j_s_h.csv') 
df = pd.read_csv('SVD_j_s_h.csv') 
print(df)

          Name         Type Tone Syllab    Jitter   Shimmer        HNR
0      myd_a_h      my_data    h      a  0.222252  0.017838  28.288537
1      myd_a_l      my_data    l      a  0.487569  0.023036  21.677873
2      myd_a_n      my_data    n      a  0.222252  0.017838  28.288537
3      4-1_a_l      my_data    l      a  5.058610  0.105972   5.959865
4        4_a_n      my_data    n      a  0.467767  0.016834  26.713612
...        ...          ...  ...    ...       ...       ...        ...
7789  2577-i_n  psychogenic    n      i  0.237235  0.013785  32.023731
7790  1479-i_h  psychogenic    h      i  0.260425  0.018988  26.772784
7791   911-a_h  psychogenic    h      a  0.600121  0.021966  23.163991
7792  1058-i_n  psychogenic    n      i  0.426018  0.017449  27.967363
7793  1425-i_l  psychogenic    l      i  0.456206  0.014702  26.299612

[7794 rows x 7 columns]


In [52]:
df = df.drop(["Name", "Tone", "Syllab"], axis=1)
df = df[df["Type"] != "my_data"]
df

Type    Jitter   Shimmer        HNR
15        healthy  1.164692  0.042058  24.772758
16        healthy  0.155393  0.011061  26.922863
17        healthy  0.224576  0.027684  27.151732
18        healthy  0.498826  0.038859  20.022510
19        healthy  0.532008  0.023150  22.705093
...           ...       ...       ...        ...
7789  psychogenic  0.237235  0.013785  32.023731
7790  psychogenic  0.260425  0.018988  26.772784
7791  psychogenic  0.600121  0.021966  23.163991
7792  psychogenic  0.426018  0.017449  27.967363
7793  psychogenic  0.456206  0.014702  26.299612

[7779 rows x 4 columns]

In [26]:
from sklearn import preprocessing

In [27]:
# Create a label encoder object 
le = preprocessing.LabelEncoder()

# Fit the encoder object (le) to a pandas field with categorical data
le.fit(df['Type'])

# Display labels
target_names = list(le.classes_)
print(target_names)

# Apply the label encoder object to a pandas column
dys_target = le.transform(df['Type']) 
print(dys_target)

['functional', 'healthy', 'hyperfunctional', 'organic', 'psychogenic']
[1 1 1 ... 4 4 4]


In [53]:
dys_data = df.drop(columns="Type").to_numpy()
dys_data

array([[1.16469189e+00, 4.20582023e-02, 2.47727582e+01],
       [1.55393233e-01, 1.10610539e-02, 2.69228625e+01],
       [2.24575675e-01, 2.76841952e-02, 2.71517319e+01],
       ...,
       [6.00121391e-01, 2.19664129e-02, 2.31639909e+01],
       [4.26018075e-01, 1.74488588e-02, 2.79673627e+01],
       [4.56206308e-01, 1.47016644e-02, 2.62996118e+01]])

In [29]:
import sklearn
from sklearn import datasets
from sklearn import svm
from sklearn import metrics

In [7]:
x = dys_data
y = dys_target

In [8]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2)

In [9]:
# print(x_train, y_train)

In [66]:
clf = svm.SVC(kernel="linear", C=7)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = metrics.accuracy_score(y_test, y_pred)
print("Linear Accuracy:", acc)

Linear Accuracy: 0.40938303341902316


In [12]:
from tqdm import tqdm

In [13]:
## 500 runs to measure the average

# linear
total = 0
for i in tqdm(range(0,500)):
    x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2)
    clf = svm.SVC(kernel="linear", C=7)
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    acc = metrics.accuracy_score(y_test, y_pred)
#     print("Linear Accuracy:", acc)
    total += acc
    
avrg = total / 500
print("Linear avrg:", avrg)

In [48]:
import numpy as np
features_names = ["Jitter", "Shimmer", "HNR"]
features_names

['Jitter', 'Shimmer', 'HNR']

In [49]:
from matplotlib import pyplot as plt

def f_importances(coef, names):
    imp = coef
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()


f_importances(clf.coef_, features_names)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
clf.coef_.shape

(10, 3)

In [58]:
imp = clf.coef_
imp

array([[ 1.71981201e-01,  5.01961510e-01,  5.90925021e-03],
       [ 8.69071746e-04,  1.87386356e-02,  2.22546543e-04],
       [ 1.87818027e-02, -3.82346593e+00,  7.38886441e-02],
       [ 8.44105598e-03, -4.77899661e-01, -1.38292220e-04],
       [-6.24716169e-01, -2.52864953e+00, -1.53762171e-02],
       [-5.71493374e-01, -2.32884241e+00, -1.67077743e-02],
       [-2.48468645e-02, -1.25142122e-01, -6.53442636e-04],
       [-1.28259130e-02,  1.33520130e-02, -4.02869337e-05],
       [ 1.99940146e-04, -1.23863721e-02,  5.82262874e-05],
       [-7.55798673e-02, -2.89921953e+00, -1.05902828e-01]])

In [61]:
names = ["Jitter", "Shimmer", "HNR"]
# imp,names = zip(*sorted(zip(imp,names)))

In [65]:
zip(*sorted(zip(imp,names)))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()